package validator

// ValidationErrorMessages : validation error message
var ValidationErrorMessages = map[string]interface{}{
	"default":  "The :field field is invalid.",
	"required": "The :field field is required.",
	"len": map[string]string{
		"int":    "The :field must be :value.",
		"uint":   "The :field must be :value.",
		"string": "The :field must be :value characters.",
		"map":    "The :field must contain :value items.",
		"slice":  "The :field must contain :value items.",
	},
	"min": map[string]string{
		"int":    "The :field must be at least :value.",
		"uint":   "The :field must be at least :value.",
		"string": "The :field must be at least :value characters.",
		"map":    "The :field must have at least :value items.",
		"slice":  "The :field must have at least :value items.",
	},
	"max": map[string]string{
		"int":    "The :field may not be greater than :value.",
		"uint":   "The :field may not be greater than :value.",
		"string": "The :field may not be greater than :value characters.",
		"map":    "The :field may not have more than :value items.",
		"slice":  "The :field may not have more than :value items.",
	},
	"eq": map[string]string{
		"int":    "The :field must be :value.",
		"uint":   "The :field must be :value.",
		"string": "The :field must be :value.",
		"map":    "The :field must contain :value items.",
		"slice":  "The :field must contain :value items.",
	},
	"ne": map[string]string{
		"int":    "The :field must not be :value.",
		"uint":   "The :field must not be :value.",
		"string": "The :field must not be :value.",
		"map":    "The :field must not contain :value items.",
		"slice":  "The :field must not contain :value items.",
	},
	"gte": map[string]string{
		"int":    "The :field must have more than or equal to :value.",
		"uint":   "The :field must have more than or equal to :value.",
		"string": "The :field must have more than or equal to :value characters.",
		"map":    "The :field must have more than or equal to :value items.",
		"slice":  "The :field must have more than or equal to :value items.",
	},
	"gt": map[string]string{
		"int":    "The :field must have more than :value.",
		"uint":   "The :field must have more than :value.",
		"string": "The :field must have more than :value characters.",
		"map":    "The :field must have more than :value items.",
		"slice":  "The :field must have more than :value items.",
	},
	"lt": map[string]string{
		"int":    "The :field may not be greater than or equal to :value.",
		"uint":   "The :field may not be greater than or equal to :value.",
		"string": "The :field may not be greater than or equal to :value characters.",
		"map":    "The :field may not have more than or equal to :value items.",
		"slice":  "The :field may not have more than or equal to :value items.",
	},
	"lte": map[string]string{
		"int":    "The :field may not be greater than :value.",
		"uint":   "The :field may not be greater than :value.",
		"string": "The :field may not be greater than :value characters.",
		"map":    "The :field may not have more than :value items.",
		"slice":  "The :field may not have more than :value items.",
	},
	"eqfield":     "The :field and :value must match.",
	"nefield":     "The :field field is invalid.",
	"alpha":       "The :field may only contain letters.",
	"alphanum":    "The :field may only contain letters and numbers.",
	"numeric":     "The :field must be a number.",
	"hexadecimal": "The :field must be a hexadecimal.",
	"hexcolor":    "The :field must be a hexcolor.",
	"rgb":         "The :field does not match the format rgb.",
	"rgba":        "The :field does not match the format rgba.",
	"hsl":         "The :field does not match the format hsl.",
	"hsla":        "The :field does not match the format hsla.",
	"email":       "The :field must be a valid email address.",
	"url":         "The :field format is invalid.",
	"uri":         "The :field format is invalid.",
	"contains":    "The selected :field is invalid.",
	"containsany": "The selected :field is invalid.",
	"excludes":    "The selected :field is invalid.",
	"excludesall": "The selected :field is invalid.",
	"isbn":        "The :field must be a valid ISBN number.",
	"uuid":        "The :field must be a valid UUID.",
	"uuid3":       "The :field must be a valid UUID3.",
	"uuid4":       "The :field must be a valid UUID4.",
	"uuid5":       "The :field must be a valid UUID5.",
	"ascii":       "The :field must be a valid IP address.",
	"latitude":    "The :field must be a valid latitude.",
	"longitude":   "The :field must be a valid longitude.",
	"ip":          "The :field must be a valid IP address.",
	"ipv4":        "The :field must be a valid IPv4 address.",
	"ipv6":        "The :field must be a valid IPv6 address.",
	"mac":         "The :field must be a valid MAC address.",
	"countrycode": "The :field is invalid.",
	"requiredif":  "The :field field is required.",
	"phonenumber": "The :field must be a valid phone number.",
}
